# -*- coding: utf-8 -*-
"""week2-A106260076-莊敏雪.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pIBHBQQH7RrsL-5YLdHBTeWlbfgNwCIU
"""

print("Hello World!")

import this